version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    # Group all npm updates into one PR
    groups:
      npm-dependencies:
        patterns:
          - "*"

    labels:
      - "dependencies"
